# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: tiipiik.smssender::lang.posts.new

# Model Form Field configuration
form: @/plugins/tiipiik/smssender/models/smssender/fields.yaml

# Model Class name
modelClass: Tiipiik\SmsSender\Models\SmsSender

# Default redirect location
defaultRedirect: tiipiik/smssender/smssender

# Create page
create:
    title: tiipiik.smssender::lang.posts.create
    redirect: tiipiik/smssender/smssender/update/:id
    redirectClose: tiipiik/smssender/smssender

# Update page
update:
    title: tiipiik.smssender::lang.posts.edit
    redirect: tiipiik/smssender/smssender
    redirectClose: tiipiik/smssender/smssender

# Preview page
preview:
    title: tiipiik.smssender::lang.posts.preview